import type { Demand, AgentInstance, AgentDefinition, DomainEvent } from '@/types'

export const AGENT_DEFINITIONS: AgentDefinition[] = [
  { id: 'pm', name: 'PM Agent', role: 'Product Manager', station: 'Product Discovery', color: '#7c6cf0', accentColor: '#9d91f5', robotVariant: 'pm' },
  { id: 'tl', name: 'TL Agent', role: 'Tech Lead', station: 'Architecture', color: '#3b82f6', accentColor: '#60a5fa', robotVariant: 'tl' },
  { id: 'dev', name: 'Dev Agent', role: 'Desenvolvedor', station: 'Frontend', color: '#22c55e', accentColor: '#4ade80', robotVariant: 'dev' },
  { id: 'qa', name: 'QA Agent', role: 'Quality Assurance', station: 'QA Lab', color: '#f59e0b', accentColor: '#fbbf24', robotVariant: 'qa' },
  { id: 'ux', name: 'UX Agent', role: 'UX Designer', station: 'UX Studio', color: '#ec4899', accentColor: '#f472b6', robotVariant: 'ux' },
  { id: 'pe', name: 'PE Agent', role: 'Prompt Engineer', station: 'Prompt Engineering', color: '#8b5cf6', accentColor: '#a78bfa', robotVariant: 'pe' },
  { id: 'sec', name: 'Security Agent', role: 'Security Reviewer', station: 'Security Review', color: '#ef4444', accentColor: '#f87171', robotVariant: 'sec' },
  { id: 'rel', name: 'Release Agent', role: 'Release Validator', station: 'Release Control', color: '#14b8a6', accentColor: '#2dd4bf', robotVariant: 'rel' },
]

export const DEMO_AGENT_INSTANCES: Record<string, AgentInstance> = {
  pm: {
    definitionId: 'pm',
    status: 'IDLE',
    currentTask: '',
    duration: 272,
    lastActivity: '04:32',
    demandId: 'DE-2024-05-15-001',
    filesAccessed: ['context/business/opea.md'],
    toolsUsed: ['Read', 'Write'],
  },
  tl: {
    definitionId: 'tl',
    status: 'IDLE',
    currentTask: '',
    duration: 378,
    lastActivity: '06:18',
    demandId: 'DE-2024-05-15-001',
    filesAccessed: ['src/api/', 'src/models/'],
    toolsUsed: ['Read', 'Bash'],
  },
  dev: {
    definitionId: 'dev',
    status: 'IDLE',
    currentTask: '',
    duration: 765,
    lastActivity: '12:45',
    demandId: 'DE-2024-05-15-001',
    filesChanged: ['src/checkout/index.tsx', 'src/checkout/FreteCalc.tsx'],
    toolsUsed: ['Edit', 'Bash'],
  },
  qa: {
    definitionId: 'qa',
    status: 'IDLE',
    currentTask: '',
    duration: 501,
    lastActivity: '08:21',
    demandId: 'DE-2024-05-15-001',
    filesChanged: ['tests/checkout.spec.ts'],
    toolsUsed: ['Write', 'Bash'],
  },
  ux: {
    definitionId: 'ux',
    status: 'IDLE',
    currentTask: '',
    duration: 453,
    lastActivity: '07:33',
    demandId: 'DE-2024-05-15-001',
    filesAccessed: ['src/components/checkout/'],
    toolsUsed: ['Read', 'Write'],
  },
  pe: {
    definitionId: 'pe',
    status: 'IDLE',
    currentTask: '',
    duration: 311,
    lastActivity: '05:11',
    demandId: 'DE-2024-05-15-001',
    filesChanged: ['.claude/agents/dev-checkout.md'],
    toolsUsed: ['Write'],
  },
  sec: { definitionId: 'sec', status: 'IDLE', currentTask: '', duration: 0, lastActivity: '--', demandId: 'DE-2024-05-15-001' },
  rel: { definitionId: 'rel', status: 'IDLE', currentTask: '', duration: 0, lastActivity: '--' },
}

export const DEMO_EVENTS: DomainEvent[] = [
  {
    id: 'ev-001', eventType: 'agent.task_completed', timestamp: new Date(Date.now() - 120000).toISOString(),
    demandId: 'DE-2024-05-15-001', agentId: 'dev', summary: 'Implementou componente de cálculo de frete',
    metadata: { file: 'src/checkout/FreteCalc.tsx', linesAdded: 87 }, correlationId: 'corr-001',
  },
  {
    id: 'ev-002', eventType: 'agent.task_completed', timestamp: new Date(Date.now() - 300000).toISOString(),
    demandId: 'DE-2024-05-15-001', agentId: 'qa', summary: 'Criou teste: cálculo de frete com CEP inválido',
    metadata: { scenario: 'negative', priority: 'high' }, correlationId: 'corr-002',
  },
  {
    id: 'ev-003', eventType: 'agent.task_completed', timestamp: new Date(Date.now() - 600000).toISOString(),
    demandId: 'DE-2024-05-15-001', agentId: 'tl', summary: 'Revisou arquitetura do módulo de pagamento',
    metadata: { decision: 'split payment service into separate module' }, correlationId: 'corr-003',
  },
  {
    id: 'ev-004', eventType: 'agent.task_completed', timestamp: new Date(Date.now() - 900000).toISOString(),
    demandId: 'DE-2024-05-15-001', agentId: 'ux', summary: 'Atualizou fluxo de checkout na UI',
    metadata: { screens: ['CartPage', 'CheckoutPage', 'ConfirmPage'] }, correlationId: 'corr-004',
  },
  {
    id: 'ev-005', eventType: 'agent.task_completed', timestamp: new Date(Date.now() - 1200000).toISOString(),
    demandId: 'DE-2024-05-15-001', agentId: 'pm', summary: 'Aprovou critérios de aceite',
    metadata: { criteria: 4, approved: 3, pending: 1 }, correlationId: 'corr-005',
  },
]

export const DEMO_DEMAND: Demand = {
  id: 'DE-2024-05-15-001',
  title: 'Implementar Checkout Inteligente',
  description: 'Implementar um fluxo de checkout inteligente com cálculo de frete em tempo real, múltiplas formas de pagamento e confirmação de pedido.',
  priority: 'HIGH',
  status: 'EXECUTION',
  requestedBy: 'PM João',
  createdAt: '2024-05-15T09:30:00Z',
  updatedAt: new Date().toISOString(),
  repository: 'opea/checkout-service',
  branch: 'feature/smart-checkout',
  dueDate: '2024-05-22T00:00:00Z',
  progress: 65,
  workflowStages: [
    { id: 'intake', label: 'Demand Intake', shortLabel: 'Intake', group: 'intake', status: 'done' },
    { id: 'triage', label: 'Triagem', shortLabel: 'Triagem', group: 'intake', status: 'done' },
    { id: 'classification', label: 'Classificação', shortLabel: 'Class.', group: 'intake', status: 'done' },
    { id: 'product_analysis', label: 'Análise de Produto', shortLabel: 'Análise', group: 'analysis', status: 'done' },
    { id: 'ambiguity', label: 'Ambiguidades', shortLabel: 'Ambig.', group: 'analysis', status: 'done' },
    { id: 'scope', label: 'Escopo', shortLabel: 'Escopo', group: 'analysis', status: 'done' },
    { id: 'out_of_scope', label: 'Fora de Escopo', shortLabel: 'F. Escopo', group: 'analysis', status: 'done' },
    { id: 'business_rules', label: 'Regras de Negócio', shortLabel: 'Regras', group: 'analysis', status: 'done' },
    { id: 'use_cases', label: 'Casos de Uso', shortLabel: 'Casos', group: 'planning', status: 'done' },
    { id: 'acceptance_criteria', label: 'Critérios de Aceite', shortLabel: 'Critérios', group: 'planning', status: 'done' },
    { id: 'prompt_engineering', label: 'Eng. de Prompt', shortLabel: 'Prompts', group: 'planning', status: 'done' },
    { id: 'technical_analysis', label: 'Análise Técnica', shortLabel: 'Técnica', group: 'planning', status: 'done' },
    { id: 'ux_analysis', label: 'Análise UX', shortLabel: 'UX', group: 'planning', status: 'done' },
    { id: 'decomposition', label: 'Decomposição', shortLabel: 'Decomp.', group: 'planning', status: 'done' },
    { id: 'agent_selection', label: 'Seleção de Agentes', shortLabel: 'Agentes', group: 'planning', status: 'done' },
    { id: 'implementation_plan', label: 'Plano de Impl.', shortLabel: 'Plano', group: 'planning', status: 'done' },
    { id: 'test_planning', label: 'Planejamento de Testes', shortLabel: 'Testes', group: 'planning', status: 'done' },
    { id: 'implementation', label: 'Implementação', shortLabel: 'Impl.', group: 'execution', status: 'active', agentId: 'dev' },
    { id: 'automated_tests', label: 'Testes Automatizados', shortLabel: 'Auto Testes', group: 'testing', status: 'active', agentId: 'qa' },
    { id: 'code_review', label: 'Revisão de Código', shortLabel: 'Code Review', group: 'testing', status: 'pending' },
    { id: 'security_review', label: 'Validação de Segurança', shortLabel: 'Segurança', group: 'testing', status: 'pending' },
    { id: 'criteria_validation', label: 'Validação de Critérios', shortLabel: 'Validação', group: 'testing', status: 'pending' },
    { id: 'fix_failures', label: 'Correção de Falhas', shortLabel: 'Correção', group: 'testing', status: 'pending' },
    { id: 'retest', label: 'Reexecução de Testes', shortLabel: 'Reteste', group: 'testing', status: 'pending' },
    { id: 'evidence', label: 'Evidências', shortLabel: 'Evidências', group: 'delivery', status: 'pending' },
    { id: 'delivery_report', label: 'Parecer de Entrega', shortLabel: 'Parecer', group: 'delivery', status: 'pending' },
    { id: 'human_approval', label: 'Aprovação Humana', shortLabel: 'Aprovação', group: 'delivery', status: 'pending' },
  ],
  acceptanceCriteria: [
    { id: 'ac-01', description: 'Usuário consegue calcular frete em tempo real', status: 'passed' },
    { id: 'ac-02', description: 'Suporta múltiplas formas de pagamento', status: 'passed' },
    { id: 'ac-03', description: 'Pedido é confirmado com sucesso', status: 'passed' },
    { id: 'ac-04', description: 'E-mails de confirmação são enviados', status: 'pending' },
  ],
  assignedAgents: ['pm', 'tl', 'dev', 'qa', 'ux', 'pe'],
  qualityGates: [
    { id: 'qg-lint',         name: 'Lint',             status: 'passed',  mandatory: true,  agentId: 'dev' },
    { id: 'qg-types',        name: 'Type Check',       status: 'passed',  mandatory: true,  agentId: 'dev' },
    { id: 'qg-unit',         name: 'Unit Tests',       status: 'pending', mandatory: true,  agentId: 'qa'  },
    { id: 'qg-integration',  name: 'Integration',      status: 'pending', mandatory: true,  agentId: 'qa'  },
    { id: 'qg-code-review',  name: 'Code Review',      status: 'pending', mandatory: true,  agentId: 'tl'  },
    { id: 'qg-security',     name: 'Security',         status: 'pending', mandatory: true,  agentId: 'sec' },
    { id: 'qg-approval',     name: 'Aprovação Humana', status: 'pending', mandatory: true,  agentId: 'pm'  },
  ],
  generatedPrompt: 'Você é um assistente especializado em desenvolver soluções de e-commerce... Seu objetivo é implementar um checkout inteligente que seja rápido, seguro...',
  technicalPlan: 'Separar checkout em módulo independente com: FreteService (adapter Correios + Melhor Envio), PaymentService (Stripe + PIX), OrderService.',
  testStats: { total: 24, passing: 18, pending: 6, failing: 0 },
  codeQuality: { score: 92, noCriticalBugs: true, coverage: 87, codeReview: 'Aprovado' },
  elapsedTime: '18h 42m',
  estimatedTotal: '28h',
  nextSteps: [
    'Finalizar testes de integração',
    'Revisão final do QA',
    'Deploy em staging',
    'Review com stakeholders',
  ],
  events: DEMO_EVENTS,
}
